### ISSUE TITLE
CI Roadmap

### ISSUE THREAD

**Issue by yqlbu** [daeuniverse/dae#156]
## Context

Constantly improve CI quality build.

## TODOs

- [x] Separate `release` build from regular build
- [x] Separate `pr-based` build from regular build
- [x] Add automation of `example.dae` to `generate-changelogs` workflow
- [x] Add `daily-preview` build
- [x] Use `shared` workflows/actions to chain reusable steps to various downstream workflows ==> `CI Modularity`

**Comment by yqlbu** [comment]
According to @MarksonHon, quoted:

> 构建与压缩这两个步骤可以用脚本去操作，方便复用

**Comment by yqlbu** [comment]
Task - `Add` automation of example.dae to generate-changelogs workflow` has been implemented in https://github.com/daeuniverse/changelogs-generator-action/pull/10

**Comment by yqlbu** [comment]
Task - `Add daily-preview build` has been implemented in #189

**Comment by yqlbu** [comment]
Task - Use `shared` workflows/actions to chain reusable steps to various downstream workflows ==> `CI Modularity` has been implemented in #190

**Comment by yqlbu** [comment]
As all TODOs have been implemented, close this issue.
